### ISSUE TITLE
Issue with default luarocks installation

### ISSUE THREAD

**Issue by yy8402** [philanc/luazen#11]
With luarocks, it is going to install luazen-0.9-1 by default, and I got an error telling "src/mono.c:48:28: error: 'for' loop initial declarations are only allowed in C99 mode". I have CentOS 7 in a docker, has the latest version (luazen-0.11-1) solved this issue? Could you update the default luarocks package at https://luarocks.org/modules/philanc/luazen?

**Comment by philanc** [comment]
Hi yy8402,
I modified the luazen build to allow the possibility to build luazen "a la carte" (see the Modular build section in the Readme).

Two rockspec files have been added to build the current stable version (v0.12) and the last github version.

I don't know if the last luazen version is still useful for your project. If it is and you face some difficulties, let me know.  

Regarding the C99 mode issue, it should be solved in the last version. I have fixed the Chacha source so that it compiles in Luarocks default mode. As far sa I know, I cannot pass compilation flags to gcc when using the "builtin" build mode, but I am not a Luarocks expert (by far!) 

Hope it still helps

--philanc
